services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - book-network
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  bsn-api:
    container_name: bsn-api
    image: alancs7/bsn-api:latest
    ports:
      - 8088:8088
    networks:
      - book-network
    depends_on:
      - postgres
  bsn-ui:
    container_name: bsn-ui
    image: alancs7/bsn-ui:latest
    ports:
      - 8080:80
    networks:
      book-network:
    depends_on:
      - bsn-api
networks:
  book-network:
    driver: bridge

volumes:
  postgres:
    driver: local